name: plotea 
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.13
  - matplotlib
  - numpy
  - pytest
  - sphinx
  - sphinx-rtd-theme
# Data science
  - pandas
  - scipy
# Geospatial
  - geopandas
  - xarray
# Visualisation
  - cartopy
# Pip  
  - pip
