name: plotea 
channels:
  - conda-forge
  - defaults
dependencies:

  - python=3.11

# STAPLES
  - autologging
  - ipykernel # python -m ipykernel install --user --name=iogeo
  - matplotlib
  - numpy
  - pandas
  - pytest
  - sphinx
  - sphinx-rtd-theme

 # GEOSPATIAL ANALYSIS
  # - geopandas
  - geojson # used by pysheds
  - xarray # numpy arrays endowed with metadata, good e.g. for netCDF4 files
  # - pygmt # it seems better to still use GMT from terminal...
