package:
  name: plotea
  version: "0.0.2"  # Adjust the version number as needed

source:
  path: .  # Assuming the source code is in the current directory

build:
  noarch: python  # if pure Python (independent of the system architecture)

requirements:
  host:
    - python
    - setuptools
  run:
    - python
    # - abc
    - autologging
    - cmocean
    - matplotlib
    - numpy    


extra:
  channels:
    - conda-forge